import type { ToolDef } from "./types"

const SIPUTZX = "https://api.siputzx.my.id"
const KYZZ = "https://api.kyzznekoo.my.id"

/** helper ambil data utama dari respons API */
const P = (path: string) => ({ resultPath: path })

export const TOOLS: ToolDef[] = [
  // ─────────── TOOLS ───────────
  {
    id: "qr",
    category: "tools",
    name: "QR Generator",
    desc: "Generate a QR code from text",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/tools/v2/qr",
    fields: [{ name: "text", label: "Text / URL", type: "text", required: true, placeholder: "https://example.com" }],
    resultKind: "image",
    renderKind: "image",
  },
  {
    id: "myip",
    category: "tools",
    name: "My IP",
    desc: "Check your IP info (optional: check a specific IP)",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/tools/ip",
    fields: [{ name: "ip", label: "IP (opsional)", type: "text", placeholder: "8.8.8.8" }],
    resultKind: "json",
    renderKind: "keyValue",
    ...P("result"),
    titleField: "query",
    metaFields: ["country", "countryCode", "regionName", "city", "zip", "isp", "org", "as", "timezone", "lat", "lon"],
  },
  {
    id: "obfuscate",
    category: "tools",
    name: "JS Obfuscate",
    desc: "Obfuscate JavaScript code",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/tools/obfuscate",
    fields: [{ name: "text", label: "JavaScript code", type: "text", required: true, placeholder: "const x = 1" }],
    resultKind: "json",
    renderKind: "codeBlock",
    ...P("result"),
  },
  {
    id: "npm",
    category: "tools",
    name: "NPM Search",
    desc: "Search npm packages",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/search/npm",
    fields: [{ name: "q", label: "Package name", type: "text", required: true, placeholder: "axios" }],
    resultKind: "json",
    renderKind: "resultList",
    ...P("data.result"),
    titleField: "name",
    descriptionField: "description",
    linkField: "link",
    metaFields: ["version", "publisher", "date", "score"],
  },
  {
    id: "github-search",
    category: "tools",
    name: "GitHub Search",
    desc: "Search GitHub repos",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/search/github",
    fields: [{ name: "q", label: "Query", type: "text", required: true, placeholder: "opencode" }],
    resultKind: "json",
    renderKind: "resultList",
    ...P("data.item"),
    titleField: "creator",
    descriptionField: "description",
    linkField: "url",
    metaFields: ["star", "language"],
  },
  {
    id: "upload-imgbb",
    category: "tools",
    name: "Upload ImgBB",
    desc: "Host an image via ImgBB",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/upload/imgbb",
    fields: [{ name: "url", label: "Image URL", type: "url", required: true, placeholder: "https://..." }],
    resultKind: "json",
    renderKind: "keyValue",
    ...P("data.url"),
    titleField: "url",
    metaFields: ["filename", "mime", "extension", "size"],
  },
  {
    id: "upload-github",
    category: "tools",
    name: "Upload GitHub",
    desc: "Host an image via GitHub",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/upload/github",
    fields: [
      { name: "url", label: "Image URL", type: "url", required: true, placeholder: "https://..." },
      { name: "accessToken", label: "GitHub token (opsional)", type: "text" },
    ],
    resultKind: "json",
    renderKind: "keyValue",
    ...P("data"),
    titleField: "url",
    metaFields: ["file", "github", "method"],
  },
  {
    id: "kodepos",
    category: "tools",
    name: "Kodepos",
    desc: "Find Indonesian postal codes",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/tools/kodepos",
    fields: [{ name: "form", label: "Kota / kecamatan", type: "text", required: true, placeholder: "jakarta" }],
    resultKind: "json",
    renderKind: "resultList",
    ...P("data"),
    titleField: "kodepos",
    descriptionField: "kecamatan",
    metaFields: ["desa", "kota", "provinsi"],
  },
  {
    id: "tempmail",
    category: "tools",
    name: "Temp Mail",
    desc: "Create a disposable email inbox",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/tools/tmpmail/v2/create",
    fields: [],
    resultKind: "json",
    renderKind: "keyValue",
  },

  // ─────────── CANVAS ───────────
  {
    id: "brat",
    category: "canvas",
    name: "Brat",
    desc: "Generate a Brat text image",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/m/brat",
    fields: [{ name: "text", label: "Text", type: "text", required: true, placeholder: "hello world" }],
    resultKind: "image",
    renderKind: "image",
  },
  {
    id: "balogo",
    category: "canvas",
    name: "Logo Maker",
    desc: "Generate a logo from text",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/maker/balogo",
    fields: [
      { name: "nama", label: "Text", type: "text", required: true, placeholder: "neostudio" },
      { name: "bgcolor", label: "Background color (opsional)", type: "text", defaultValue: "#0B0B0F" },
      { name: "color", label: "Text color (opsional)", type: "text", defaultValue: "#F5DEB3" },
    ],
    resultKind: "image",
    renderKind: "image",
  },
  {
    id: "iqc",
    category: "canvas",
    name: "IQC",
    desc: "Generate an IQ card image",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/image/iqc",
    fields: [
      { name: "text", label: "Text", type: "text", required: true, placeholder: "Budi" },
      { name: "avatar", label: "Avatar URL (opsional)", type: "url" },
    ],
    resultKind: "image",
    renderKind: "image",
  },
  {
    id: "ppcouple",
    category: "canvas",
    name: "PP Couple",
    desc: "Random couple profile pics",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/image/ppcouple",
    fields: [],
    resultKind: "json",
    renderKind: "imagePair",
    ...P("result"),
    leftField: "cowo",
    rightField: "cewe",
  },
  {
    id: "story-ig",
    category: "canvas",
    name: "IG Story",
    desc: "Generate an IG story template",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/canvas/v2/storyig",
    fields: [
      { name: "username", label: "Username", type: "text", required: true },
      { name: "text", label: "Text", type: "text" },
      { name: "avatar", label: "Avatar URL", type: "url" },
    ],
    resultKind: "image",
    renderKind: "image",
  },
  {
    id: "fake-ig",
    category: "canvas",
    name: "Fake IG",
    desc: "Fake Instagram post meme",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/canvas/v2/fake-ig",
    fields: [
      { name: "username", label: "Username", type: "text", required: true },
      { name: "avatar", label: "Avatar URL", type: "url" },
    ],
    resultKind: "image",
    renderKind: "image",
  },
  {
    id: "wanted",
    category: "canvas",
    name: "Wanted",
    desc: "WANTED poster",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/editor/wanted",
    fields: [
      { name: "url", label: "Image URL", type: "url", required: true },
      { name: "text", label: "Name", type: "text", placeholder: "Wanted" },
    ],
    resultKind: "image",
    renderKind: "image",
  },
  {
    id: "wasted",
    category: "canvas",
    name: "Wasted",
    desc: "Wasted meme overlay",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/editor/wasted",
    fields: [
      { name: "url", label: "Image URL", type: "url", required: true },
      { name: "text", label: "Text", type: "text", placeholder: "WASTED" },
    ],
    resultKind: "image",
    renderKind: "image",
  },
  {
    id: "upscale-uhd",
    category: "canvas",
    name: "Upscale UHD",
    desc: "Upscale an image to UHD",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/upscale/v5/uhd",
    fields: [{ name: "url", label: "Image URL", type: "url", required: true }],
    resultKind: "image",
    renderKind: "image",
  },
  {
    id: "hdfoto",
    category: "canvas",
    name: "HD Foto",
    desc: "Enhance a photo to HD",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/upscale/hdfoto",
    fields: [{ name: "url", label: "Image URL", type: "url", required: true }],
    resultKind: "image",
    renderKind: "image",
  },
  {
    id: "sertifikat",
    category: "canvas",
    name: "Certificate",
    desc: "Generate a certificate",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/image/sertifikat",
    fields: [{ name: "text", label: "Nama", type: "text", required: true }],
    resultKind: "image",
    renderKind: "image",
  },
  {
    id: "faceblur",
    category: "canvas",
    name: "Face Blur",
    desc: "Blur faces in an image",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/editor/faceblur",
    fields: [{ name: "url", label: "Image URL", type: "url", required: true }],
    resultKind: "image",
    renderKind: "image",
  },
  {
    id: "removebg",
    category: "canvas",
    name: "Remove Background",
    desc: "Remove image background",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/tools/rbg",
    fields: [{ name: "url", label: "Image URL", type: "url", required: true }],
    resultKind: "image",
    renderKind: "image",
  },

  // ─────────── DOWNLOADER ───────────
  {
    id: "tiktok",
    category: "downloader",
    name: "TikTok",
    desc: "Download TikTok video",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/downloader/v2/tiktok",
    fields: [{ name: "url", label: "URL", type: "url", required: true, placeholder: "https://tiktok.com/..." }],
    resultKind: "json",
    renderKind: "downloadCard",
    ...P("data"),
    titleField: "title",
    descriptionField: "author.nickname",
    thumbnailField: "cover",
    downloadField: "play",
    downloadFields: ["play", "wmplay", "music"],
    metaFields: ["duration"],
    fallbackToolId: "all-dl",
  },
  {
    id: "instagram",
    category: "downloader",
    name: "Instagram",
    desc: "Download Instagram media",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/d/sssinstagram",
    fields: [{ name: "url", label: "URL", type: "url", required: true, placeholder: "https://instagram.com/..." }],
    resultKind: "json",
    renderKind: "downloadCard",
    ...P("data"),
    titleField: "title",
    thumbnailField: "thumbnail",
    downloadField: "url",
    fallbackToolId: "all-dl",
  },
  {
    id: "facebook",
    category: "downloader",
    name: "Facebook",
    desc: "Download Facebook video",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/d/facebook",
    fields: [{ name: "url", label: "URL", type: "url", required: true, placeholder: "https://facebook.com/..." }],
    resultKind: "json",
    renderKind: "downloadCard",
    ...P("data"),
    titleField: "title",
    thumbnailField: "thumbnail",
    downloadField: "url",
    fallbackToolId: "all-dl",
  },
  {
    id: "capcut",
    category: "downloader",
    name: "CapCut",
    desc: "Download CapCut template",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/d/capcut",
    fields: [{ name: "url", label: "URL", type: "url", required: true }],
    resultKind: "json",
    renderKind: "downloadCard",
    ...P("data"),
    titleField: "title",
    downloadField: "url",
    fallbackToolId: "all-dl",
  },
  {
    id: "gdrive",
    category: "downloader",
    name: "Google Drive",
    desc: "Get Google Drive file",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/d/gdrive",
    fields: [{ name: "url", label: "URL", type: "url", required: true, placeholder: "https://drive.google.com/..." }],
    resultKind: "json",
    renderKind: "downloadCard",
    ...P("data"),
    titleField: "title",
    downloadField: "url",
    fallbackToolId: "all-dl",
  },
  {
    id: "savefrom",
    category: "downloader",
    name: "SaveFrom",
    desc: "Universal downloader",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/d/savefrom",
    fields: [{ name: "url", label: "URL", type: "url", required: true, placeholder: "https://youtube.com/..." }],
    resultKind: "json",
    renderKind: "downloadCard",
    ...P("data"),
    titleField: "title",
    downloadField: "url",
    fallbackToolId: "all-dl",
  },
  {
    id: "snackvideo",
    category: "downloader",
    name: "SnackVideo",
    desc: "Download SnackVideo",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/downloader/snackvideo",
    fields: [{ name: "url", label: "URL", type: "url", required: true, placeholder: "https://snackvideo.com/..." }],
    resultKind: "json",
    renderKind: "downloadCard",
    ...P("data"),
    titleField: "title",
    downloadField: "url",
  },
  {
    id: "spotify-dl",
    category: "downloader",
    name: "Spotify",
    desc: "Download Spotify track",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/downloader/spotify",
    fields: [{ name: "url", label: "URL", type: "url", required: true, placeholder: "https://open.spotify.com/..." }],
    resultKind: "json",
    renderKind: "downloadCard",
    ...P("data"),
    titleField: "metadata.name",
    descriptionField: "metadata.artist",
    thumbnailField: "metadata.image",
    downloadField: "url",
    metaFields: ["metadata.duration", "metadata.album", "metadata.release_year"],
  },
  {
    id: "ytmp3",
    category: "downloader",
    name: "YouTube MP3",
    desc: "YouTube to MP3",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/downloader/ytmp3",
    fields: [{ name: "url", label: "URL", type: "url", required: true, placeholder: "https://youtube.com/watch?v=..." }],
    resultKind: "json",
    renderKind: "downloadCard",
    ...P("data"),
    titleField: "title",
    downloadField: "url",
  },
  {
    id: "all-dl",
    category: "downloader",
    name: "All-in-One",
    desc: "Universal downloader",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/downloader/all",
    fields: [{ name: "url", label: "URL", type: "url", required: true, placeholder: "https://..." }],
    resultKind: "json",
    renderKind: "downloadCard",
    ...P("data"),
    titleField: "title",
    downloadField: "url",
  },

  // ─────────── NEWS & INFO ───────────
  {
    id: "berita-cnn",
    category: "news",
    name: "CNN Indonesia",
    desc: "Berita terbaru CNN Indonesia",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/berita/cnn",
    fields: [],
    resultKind: "json",
    renderKind: "articleList",
    ...P("data"),
    titleField: "title",
    descriptionField: "image_thumbnail",
    imageField: "image_thumbnail",
    linkField: "link",
    metaFields: ["slug", "image_full"],
  },
  {
    id: "berita-kompas",
    category: "news",
    name: "Kompas",
    desc: "Berita terbaru Kompas",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/berita/kompas",
    fields: [],
    resultKind: "json",
    renderKind: "articleList",
    ...P("data"),
  },
  {
    id: "berita-liputan6",
    category: "news",
    name: "Liputan6",
    desc: "Berita terbaru Liputan6",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/berita/liputan6",
    fields: [],
    resultKind: "json",
    renderKind: "articleList",
    ...P("data"),
  },
  {
    id: "berita-antara",
    category: "news",
    name: "Antara",
    desc: "Berita terbaru Antara",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/berita/antara",
    fields: [],
    resultKind: "json",
    renderKind: "articleList",
    ...P("data"),
  },
  {
    id: "berita-suara",
    category: "news",
    name: "Suara",
    desc: "Berita terbaru Suara",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/berita/suara",
    fields: [],
    resultKind: "json",
    renderKind: "articleList",
    ...P("data"),
  },
  {
    id: "berita-sindonews",
    category: "news",
    name: "Sindo News",
    desc: "Berita terbaru SindoNews",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/berita/sindonews",
    fields: [],
    resultKind: "json",
    renderKind: "articleList",
    ...P("data"),
  },
  {
    id: "berita-merdeka",
    category: "news",
    name: "Merdeka",
    desc: "Berita terbaru Merdeka",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/berita/merdeka",
    fields: [],
    resultKind: "json",
    renderKind: "articleList",
    ...P("data"),
  },
  {
    id: "berita-tribun",
    category: "news",
    name: "Tribunnews",
    desc: "Berita terbaru Tribunnews",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/berita/tribunnews",
    fields: [],
    resultKind: "json",
    renderKind: "articleList",
    ...P("data"),
  },
  {
    id: "berita-cnbc",
    category: "news",
    name: "CNBC Indonesia",
    desc: "Berita CNBC Indonesia",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/berita/cnbcindonesia",
    fields: [],
    resultKind: "json",
    renderKind: "articleList",
    ...P("data"),
  },
  {
    id: "bmkg",
    category: "news",
    name: "BMKG",
    desc: "Info cuaca & gempa BMKG",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/info/bmkg",
    fields: [],
    resultKind: "json",
    renderKind: "resultList",
  },
  {
    id: "jadwaltv",
    category: "news",
    name: "Jadwal TV",
    desc: "Jadwal acara TV",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/info/jadwaltv",
    fields: [],
    resultKind: "json",
    renderKind: "resultList",
  },
  {
    id: "sholat",
    category: "news",
    name: "Jadwal Sholat",
    desc: "Jadwal sholat per kota",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/search/sholat",
    fields: [{ name: "kota", label: "Kota", type: "text", required: true, placeholder: "jakarta" }],
    resultKind: "json",
    renderKind: "prayerTimes",
    ...P("data.result"),
    titleField: "lokasi",
    metaFields: ["daerah", "negara", "timezone", "method"],
    jadwalField: "jadwal",
  },

  // ─────────── GAMES & FUN ───────────
  {
    id: "tebak-gambar",
    category: "games",
    name: "Tebak Gambar",
    desc: "Guess the picture",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/games/tebakgambar",
    fields: [],
    resultKind: "json",
    renderKind: "resultList",
    imageField: "img",
    titleField: "soal",
    descriptionField: "jawaban",
  },
  {
    id: "family100",
    category: "games",
    name: "Family 100",
    desc: "Family 100 quiz",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/games/family100",
    fields: [],
    resultKind: "json",
    renderKind: "resultList",
  },
  {
    id: "maths",
    category: "games",
    name: "Kuis Matematika",
    desc: "Soal matematika sesuai level",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/game/maths",
    fields: [
      {
        name: "level",
        label: "Level",
        type: "select",
        required: true,
        options: ["easy", "medium", "hard", "extreme", "impossible"],
      },
    ],
    resultKind: "json",
    renderKind: "quiz",
    ...P("data"),
    questionField: "question",
    answerField: "answer",
    metaFields: ["mode", "time", "bonus"],
  },
  {
    id: "susun-kata",
    category: "games",
    name: "Susun Kata",
    desc: "Rearrange the word",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/games/susunkata",
    fields: [],
    resultKind: "json",
    renderKind: "resultList",
  },
  {
    id: "cak-lontong",
    category: "games",
    name: "Cak Lontong",
    desc: "Cak Lontong quiz",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/games/caklontong",
    fields: [],
    resultKind: "json",
    renderKind: "resultList",
  },
  {
    id: "asah-otak",
    category: "games",
    name: "Asah Otak",
    desc: "Brain teaser",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/games/asahotak",
    fields: [],
    resultKind: "json",
    renderKind: "resultList",
  },
  {
    id: "quote-anime",
    category: "games",
    name: "Quote Anime",
    desc: "Random anime quote",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/r/quotesanime",
    fields: [],
    resultKind: "json",
    renderKind: "quoteCard",
    titleField: "quote",
    ...P("data"),
  },
  {
    id: "blue-archive",
    category: "games",
    name: "Blue Archive",
    desc: "Random Blue Archive",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/r/blue-archive",
    fields: [],
    resultKind: "json",
    renderKind: "mediaList",
  },

  // ─────────── PRIMBON ───────────
  {
    id: "arti-nama",
    category: "primbon",
    name: "Arti Nama",
    desc: "Meaning of your name",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/primbon/artinama",
    fields: [{ name: "nama", label: "Nama", type: "text", required: true, placeholder: "Budi" }],
    resultKind: "json",
    renderKind: "resultList",
  },
  {
    id: "kecocokan",
    category: "primbon",
    name: "Kecocokan Pasangan",
    desc: "Couple compatibility",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/primbon/kecocokan_nama_pasangan",
    fields: [
      { name: "nama1", label: "Nama kamu", type: "text", required: true },
      { name: "nama2", label: "Nama pasangan", type: "text", required: true },
    ],
    resultKind: "json",
    renderKind: "resultList",
  },
  {
    id: "zodiak",
    category: "primbon",
    name: "Zodiak",
    desc: "Zodiac fortune",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/primbon/zodiak",
    fields: [
      {
        name: "zodiak",
        label: "Zodiak",
        type: "select",
        required: true,
        options: ["aries", "taurus", "gemini", "cancer", "leo", "virgo", "libra", "scorpio", "sagitarius", "capricorn", "aquarius", "pisces"],
      },
    ],
    resultKind: "json",
    renderKind: "resultList",
  },

  // ─────────── SEARCH ───────────
  {
    id: "yt-search",
    category: "search",
    name: "YouTube",
    desc: "Search videos",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/s/youtube",
    fields: [{ name: "query", label: "Query", type: "text", required: true, placeholder: "naruto opening" }],
    resultKind: "json",
    renderKind: "resultList",
  },
  {
    id: "pinterest-search",
    category: "search",
    name: "Pinterest",
    desc: "Search images",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/s/pinterest",
    fields: [{ name: "query", label: "Query", type: "text", required: true, placeholder: "anime" }],
    resultKind: "json",
    renderKind: "mediaList",
  },
  {
    id: "resep",
    category: "search",
    name: "Resep",
    desc: "Find recipes",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/s/resep",
    fields: [{ name: "query", label: "Query", type: "text", required: true, placeholder: "rendang" }],
    resultKind: "json",
    renderKind: "resultList",
  },
  {
    id: "apple-music",
    category: "search",
    name: "Apple Music",
    desc: "Search Apple Music",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/search/applemusic",
    fields: [{ name: "q", label: "Query", type: "text", required: true, placeholder: "coldplay" }],
    resultKind: "json",
    renderKind: "resultList",
  },
  {
    id: "spotify-search",
    category: "search",
    name: "Spotify",
    desc: "Search Spotify",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/search/v2/spotify",
    fields: [{ name: "q", label: "Query", type: "text", required: true, placeholder: "coldplay" }],
    resultKind: "json",
    renderKind: "resultList",
    ...P("songs"),
    titleField: "title",
    descriptionField: "artist",
    imageField: "thumbnail",
    linkField: "url",
  },
  {
    id: "grup-wa",
    category: "search",
    name: "Grup WA",
    desc: "Find WhatsApp groups",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/search/group",
    fields: [{ name: "q", label: "Query", type: "text", required: true, placeholder: "indonesia" }],
    resultKind: "json",
    renderKind: "resultList",
    ...P("data"),
    titleField: "name",
    descriptionField: "description",
    imageField: "thumbnail",
    linkField: "join_url",
  },

  // ─────────── STALKER ───────────
  {
    id: "stalk-github",
    category: "stalker",
    name: "GitHub",
    desc: "Lookup GitHub profile",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/stalk/github",
    fields: [{ name: "user", label: "Username", type: "text", required: true, placeholder: "torvalds" }],
    resultKind: "json",
    renderKind: "profileCard",
    titleField: "nickname",
    descriptionField: "bio",
    imageField: "profile_pic",
    linkField: "html_url",
    ...P("data"),
    metaFields: ["username", "id", "followers", "following", "public_repos", "type"],
  },
  {
    id: "stalk-twitter",
    category: "stalker",
    name: "Twitter / X",
    desc: "Lookup Twitter profile",
    source: "siputzx",
    baseUrl: SIPUTZX,
    path: "/api/stalk/twitter",
    fields: [{ name: "user", label: "Username", type: "text", required: true, placeholder: "elonmusk" }],
    resultKind: "json",
    renderKind: "profileCard",
    ...P("data"),
  },
  {
    id: "stalk-threads",
    category: "stalker",
    name: "Threads",
    desc: "Lookup Threads profile",
    source: "kyzznekoo",
    baseUrl: KYZZ,
    path: "/api/stalker/threads",
    fields: [{ name: "q", label: "Username", type: "text", required: true, placeholder: "meta" }],
    resultKind: "json",
    renderKind: "profileCard",
    ...P("result"),
    titleField: "name",
    descriptionField: "bio",
    imageField: "profile_picture",
  },
]
